Add font tarballs to repository
endlessm/endless-sdk-flatpak pull request #22
Opened 2017-11-10 15:15 UTC by xjuan

This avoids checksum errors everytime a font changes upstream.
Use fonts/download_fonts.sh to update fonts when desired.

https://phabricator.endlessm.com/T19905

2017-11-10 16:16 UTC, ebassi commented
It would be neat if you could modify the script that generates the manifest to automatically get the SHA checksum of each font package and fill up the `sha256` field in the JSON file.

2017-11-13 15:32 UTC, ebassi requested changes

2017-11-13 15:32 UTC, ebassi commented on generate-manifest.py
> +    data['modules'].append({ 'name': 'default-theme-fonts',
I'd rather have `data['modules'].prepend()` here, for two reasons:

 - early failure
 - keep the `os-release` module at the end, as it's the last part of the build process

2017-11-13 15:32 UTC, ebassi commented on fonts/download_fonts.sh
> +GOOGLE_FONTS=(Fira+Sans Lato Libre+Baskerville Merriweather Noto+Sans Noto+Serif Raleway Roboto)
Can we add this as a `Makefile` rule, instead?

2017-11-13 15:32 UTC, ebassi commented on generate-manifest.py
> +    sources = [ { 'type': 'file', 'path': 'fonts-makefile', 'dest-filename': 'Makefile' } ]
Since we're updating the manifest, I think we should also drop the `fonts-makefile` hack, and use `"build": "simple"`.

2017-11-13 22:00 UTC, ptomato approved these changes
Looks good, one style nitpick but no need to block the pull request on it.

2017-11-13 22:00 UTC, ptomato commented on generate-manifest.py
> +    with open(filename, 'rb') as file:
For next time: `file` is a built-in in Python, so it's better not to override it

2017-11-13 22:00 UTC, merged