Add GtkCssImageSurface cache patch
endlessm/endless-sdk-flatpak pull request #24
Opened 2017-12-29 20:44 UTC by xjuan

This will improve knowledge apps performance a lot for apps with an image as background.

https://phabricator.endlessm.com/T19405

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2017-12-29 20:44 UTC, eos-shell-build commented
Can one of the admins verify this patch?

2018-01-04 00:37 UTC, ptomato requested changes
Needs to have the updated version of the patch from https://bugzilla.gnome.org/attachment.cgi?id=366214&action=diff ?

I also left a couple of comments there.

2018-01-05 18:42 UTC, xjuan commented
Patch updated

2018-01-09 02:19 UTC, ptomato approved these changes
It's been accepted upstream, let's take it.

2018-01-09 02:19 UTC, merged