Generate the SDK manifest using Python
endlessm/endless-sdk-flatpak pull request #39
Opened 2018-03-14 17:41 UTC by ebassi

We're doing two passes to generate the SDK manifest: first from the
Makefile and then from the generate-manifest Python script. The script,
incidentally, overwrites some of the substitutions we perform from the
Makefile.

Let's move the manifest munging to the Python script only.

We need to still use the Makefile pattern substitution for various
ancillary files, so we need to use a different extension for the
manifest, to avoid Make getting confused.

2018-03-14 19:00 UTC, ptomato requested changes
- Is there anything that can be removed from the manifest template now? It might be a good idea to get rid of the substitutions that are just overwritten by the generate script.
- Needs a corresponding change in the `jenkins-flapjack-ci` script in eos-build, and in the example config file in flapjack.

2018-03-14 19:00 UTC, ptomato commented on generate-manifest.py
> +def edit_manifest(data, arch, branch, runtime_version, fdo_version):
`fdo_version` doesn't seem to be used?

2018-04-12 09:21 UTC, ebassi commented
This fell off my radar; I've rewritten the gtk3 patch handling a bit so it's not terrible, and dropped the `--fdo-runtime` option, as it was a leftover from a previous iteration.

2018-04-12 21:06 UTC, ptomato approved these changes

2018-04-12 21:06 UTC, merged